### ISSUE TITLE
Allow all existing shortlinks to be edited

### ISSUE THREAD

**Issue by nazmulidris** [r3bl-org/shortlink#11]
Provide a nice table / grid view that allows each shortlink to be seen and edited or deleted. The idea here is that you might want to merge or prune a few entries. And you don't want to do a full export to JSON, modify that, and then re-import it.

**Comment by soykot2910** [comment]
@nazmulidris  I'd like to request assignment to this issue. Could you please assign it to me?

**Comment by nazmulidris** [comment]
@soykot2910 Done! 🎉  And thank you! 👍🏽

**Comment by soykot2910** [comment]
@nazmulidris  Is this design okay, or does it need to be updated?
![image](https://github.com/r3bl-org/shortlink/assets/44709658/64e64ecf-3f7d-425c-a443-da668a90e68e)

**Comment by nazmulidris** [comment]
@soykot2910 Thank you for sharing a screenshot of the work so far. I like it. 

This makes me think that we should an "Edit" button on the main popup UI so that this edit "state" only appears after they click on that button. If they don't click on the button then they get the current "read-only" view of the shortlinks.

![image](https://github.com/r3bl-org/shortlink/assets/2966499/8757325c-81a8-4078-a162-a461b6eb2790)

What do you think?

**Comment by soykot2910** [comment]
Thank you for your feedback. I agree that adding an 'Edit' button in popup UI would make the user experience more  friendly. I'll work on implementing this improvement.

**Comment by nazmulidris** [comment]
@soykot2910 That sounds awesome! In the future, we might add some features to make the entire UI navigatable by keyboard, so mouse interaction isn't needed. So we could have a keyboard shortcut binding to activate "Edit" in addition to someone pressing the button.

**Comment by soykot2910** [comment]
First step
![image](https://github.com/r3bl-org/shortlink/assets/44709658/8ba3aca5-70b9-4654-9200-212d93f77e8b)
Second step
![image](https://github.com/r3bl-org/shortlink/assets/44709658/64e64ecf-3f7d-425c-a443-da668a90e68e)

@nazmulidris Do you have any preference regarding design?

**Comment by nazmulidris** [comment]
@soykot2910 that looks great! 2 questions:
1) When someone clicks on <kdb>Edit</kdb> what do they see?
2) When someone clicks on <kdb>Delete</kdb> do they get a confirmation prompt? Also if they choose to delete something, does the popup close at that point or allow them to continue editing their shortlinks. In which case we might need a "Close" button or the user can just click anywhere outside the popup?

**Comment by soykot2910** [comment]
When someone click on edit button.They will show this screen.
![image](https://github.com/r3bl-org/shortlink/assets/44709658/e0a38789-3f16-4895-93c2-ec94d0fbefd5)

When someone click on Delete, They will show a confirmation prompt.
![image](https://github.com/r3bl-org/shortlink/assets/44709658/0452ed83-26db-49c5-9cf9-4e64caf59fd1)

if someone delete something popup will still open. If user click outside popup it will close automatically.

**Comment by nazmulidris** [comment]
@soykot2910 That looks great. One small question is do we let the user get out of "edit mode" once they have entered it? They enter "edit mode" when they click on the <kbd>Edit Shortlinks</kbd> button at the very start of this journey.

**Comment by soykot2910** [comment]
Did you suggest adding a 'Go Back' link on this screen?
![image](https://github.com/r3bl-org/shortlink/assets/44709658/64e64ecf-3f7d-425c-a443-da668a90e68e)

**Comment by nazmulidris** [comment]
> Did you suggest adding a 'Go Back' link on this screen? ![image](https://user-images.githubusercontent.com/44709658/272037281-64e64ecf-3f7d-425c-a443-da668a90e68e.png)

I think so. Having a "Go Back" (or "Finish editing") button might allow the user to get out of editing mode and back to the "normal" flow of using the popup.

**Comment by soykot2910** [comment]
@nazmulidris  [PR](https://github.com/r3bl-org/shortlink/pull/19) for this issue.
