### ISSUE TITLE
Add ESLint for Code Quality Improvement.

### ISSUE THREAD

**Issue by SaurabPoudel** [r3bl-org/shortlink#21]
Description: 
ESLint is a tool that statically analyzes JavaScript code to identify and report potential errors, enforce coding conventions, and improve code quality by applying a set of configurable rules. It helps developers catch and fix issues early in the development process, leading to cleaner and more maintainable code.

Things to Consider:
ESLint Rules should created in such a way that it insures good typescript practices in the code base.

Acceptance Criteria:
-ESLint is successfully integrated into the project.
-The project's code base is properly linted, and all existing code conforms to the linting rules.
-A README or documentation is updated to include information on how to use and configure ESLint for the project.

**Comment by SaurabPoudel** [comment]
@nazmulidris Can I work on this issue ?

**Comment by nazmulidris** [comment]
Since this is entirely a Typescript project, we have to make sure that ESLint is configured for Typescript. Also, it would be beneficial to make this part of the CI/CD flow. Thoughts on this?

**Comment by SaurabPoudel** [comment]
I completely agree on this . Can I start working on this issue from tomorrow ?

**Comment by nazmulidris** [comment]
@SaurabPoudel That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

Also, please associate your PR and issue using this technique: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
