### ISSUE TITLE
Provide a way to search / filter shortlinks

### ISSUE THREAD

**Issue by nazmulidris** [r3bl-org/shortlink#24]
Currently the extension shows all shortlinks in the UI all at once. This works if there are 20 or 30 links. However, if there are 50 or more, then this becomes difficult to find what a user might be looking for.

It would be great to have a text field that allows the user to type a string. As they type, this can be used to filter what shortlinks are shown in the UI.

**Comment by dipushrestha** [comment]
Hi @nazmulidris, I would like to work on this.

**Comment by nazmulidris** [comment]
Hi 👋🏽 @dipushrestha , this issue is all yours 👍🏽 . Please take a look at our [contributor guide](https://github.com/r3bl-org/r3bl_rs_utils/blob/main/CONTRIBUTING.md#commit-message-guidelines). And we have a [discord server](https://discord.gg/8M2ePAevaM) if you would like to chat about the issue or PR.

Also, please associate your PR and issue using this technique: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by dipushrestha** [comment]
@nazmulidris I've raised a PR. Please take a look at it.

**Comment by nazmulidris** [comment]
@dipushrestha Thank you 🙏🏽 🎉 I will take a look at this in the next day or so.

**Comment by nazmulidris** [comment]
@dipushrestha Great work! 🎉
