### ISSUE TITLE
Allow mouse click in popup to open tabs

### ISSUE THREAD

**Issue by nazmulidris** [r3bl-org/shortlink#3]
In the popup, currently all the shortlink names are displayed. But they aren't clickable. Make them clickable, so that a user can open tabs with their mouse & not have to type anything.

Optional - Further refinement would be to allow <kbd>Tab</kbd> focus traversal and <kdb>Enter</kbd> to open the tabs themselves.

**Comment by JoHeyJo** [comment]
I'm going to take a crack at this!

**Comment by nazmulidris** [comment]
@JoHeyJo Awesome! This is assigned to you! 👍🏽

**Comment by JoHeyJo** [comment]
@nazmulidris I'll PR on Sunday so it counts towards Hacktoberfest, as long as you don't mind. Also, how do you feel if I make the "Optional feature" a separate issue? I also wouldn't mind taking a crack at that.

**Comment by nazmulidris** [comment]
@JoHeyJo PR on Sunday sounds great! I will be sure to mark the PR with `hacktoberfest-accepted` label 👍🏽 .

And making the optional feature a separate issue sounds great as well! 🙏🏽

**Comment by nazmulidris** [comment]
@JoHeyJo I just went through a major refactor of the code base ("promise-ifying" the chrome.storage API so it is easy to use), so hopefully this will make it easier to work with.

**Comment by nazmulidris** [comment]
@JoHeyJo Also if you like to chat about this issue or PR this is the discord server for the project: https://discord.gg/UejyhKfx
