### ISSUE TITLE
When a shortlink has lots of URLs, they spill over out of the container of the popup, and it should not do this

### ISSUE THREAD

**Issue by nazmulidris** [r3bl-org/shortlink#33]
![image](https://github.com/r3bl-org/shortlink/assets/2966499/de6bdb9f-ca14-4bb3-ae4c-d6951679e66b)

**Comment by voodoods** [comment]
Hi @nazmulidris! I prepared a fix proposal for this issue in PR #34 , please have a look and let me know what you think :)

**Comment by nazmulidris** [comment]
@voodoods That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
